theme: minima
title: Henry Xiao's personal blog
description: Data. AI. Shenanigans.
author: Henry Xiao
github_username:  Henry-Xiao-HX
linkedin_username: henry-xiao-hx
instagram_username: henry_in_the_kitchen